### ISSUE TITLE
Add option for LAN/SteamCache IP

### ISSUE THREAD

**Issue by nuhll** [lancachenet/sniproxy#2]
Hi,
im using your docker(s) in Unraid.

Problem is port 80 and 443 is reserved for Unraid, so i need to br0 it to other IPs. In all other Dockers i can set the correct IPs and its working like a charm. 

Only Origin doesnt cache, so i guess its because 
STEAMCACHE_IP

nor

LANCACHE_IP

does work in Sniproxy.

If i miss a already there variable please tell me, if there is not such an variable, please add them! :)

PS: I also worte an email to origin if they change their downloads behaivor, lets see if they change something, so we dont need to break the https anymore.

**Comment by JasonRivers** [comment]
I'm not sure I fully understand the issue you're having here, The sniproxy doesn't know (or care) what the cache IP is, This simply passes https traffic to where it should go and bypasses the caching system altogether. If you need the sniproxy to listen on a specific IP, then you can change the  -p at docker run to run on that IP. The IP it listens on must be the same IP on the network that the cache service listens on, this is because the DNS will point to the same IP for both http and https traffic (cache and https traffic).
